// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Pattern = 1,
  Patgrp = 2,
  Patatom = 3,
  Repcount = 4,
  Number = 5,
  Patcode = 6,
  Strlit = 7,
  Escdoublequote = 8,
  Alternation = 9
