// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Pattern = 1,
  Patatom = 2,
  Repcount = 3,
  Patcode = 4,
  Strlit = 5,
  Escquote = 6,
  Alternation = 7
