// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$hOQOPOOOVOPOOO_OPO'#C`OmOPO'#C`O{OPO'#C_OOOO'#Cf'#CfO!WOPO'#C^QOOOOOO!iOPO,58zOOOO,58z,58zO!wOQO'#CcOVOPO'#CeOOOO,58y,58yOOOO-E6d-E6dOOOO1G.f1G.fOOOO'#Cg'#CgO#SOQO,58}OOOO,58},58}O#_OPO,59POOOO-E6e-E6eOOOO1G.i1G.iOVOPO'#ChO#gOPO1G.kOOOO1G.k1G.kOOOO,59S,59SOOOO-E6f-E6fOOOO7+$V7+$V",
  stateData: "#o~O^PO~OTQO_RO~O_WOUSX`SXbSX~OTXOUSX`SXbSX~OU[O`YObZO~OTQO_RO]QXcQXdQX~OT^OUSa`SabSa~OW_O`aOa_O~OW_O`dOa_O~OceOdgO~OceOdjO~O",
  goto: "![]PP^gmPPsPsv!O!UQVPQbZRheXTPUZeXSPUZeR[SUUPZeR]UQ`YRc`QfbRif",
  nodeNames: "⚠ Pattern Patgrp Patatom Repcount Number Patcode Strlit Escdoublequote Alternation",
  maxTerm: 20,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "%s~R|Or#{rs$Qsx#{xy$_yz$fz|#{|}$m}!O#{!O!P$t!P!Q#{!Q![${![!a#{!a!b%_!b!c#{!c!d%f!d!e#{!e!f%f!f!g#{!g!h%f!h!n#{!n!o%f!o!p#{!p!q%f!q!r#{!r!s%f!s!w#{!w!x%f!x#T#{#T#U%f#U#V#{#V#W%f#W#X#{#X#Y%f#Y#`#{#`#a%f#a#b#{#b#c%f#c#d#{#d#e%f#e#i#{#i#j%f#j;'S#{;'S;=`%m<%lO#{Q$QOaQ~$VP`~rs$Y~$_OW~R$fObPaQR$mOdPaQR$tOcPaQR${O_PaQR%SPTPaQ!Q![%VP%[PTP!Q![%VR%fO^PaQR%mOUPaQQ%pP;=`<%l#{",
  tokenizers: [0, 1],
  topRules: {"Pattern":[0,1]},
  tokenPrec: 0
})
