// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Pattern = 1,
  Patatom = 2,
  Repcount = 3,
  Number = 4,
  Patcode = 5,
  Strlit = 6,
  Escdoublequote = 7,
  Alternation = 8
